FROM node:16.16.0
COPY . /app
WORKDIR /app

ENV TIMEZONE=America/Sao_Paulo
ENV MONGOO_URI=

ENV MONGOO_URI=
ENV IOT_CORE_CERTPATH_URL=
ENV IOT_CORE_KEYPATH_URL=
ENV IOT_CORE_CATH_URL=
ENV IOT_CORE_HOST=
ENV IOT_CORE_CLIENT_ID=
ENV IOT_CORE_TOPIC=

ENV PM2_PUBLIC_KEY=
ENV PM2_SECRET_KEY=

RUN npm install --force
RUN npm run build 
RUN npm install pm2 -g && npm run build
CMD ["pm2-runtime", "dist/index.js"]
